import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { chromium } from "playwright";
import { createWorkspaceServer } from "../apps/workspace/src/server.js";
import type { ImageGenerator } from "../packages/image-generation/src/index.js";

const ONE_PX = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Z1ZQAAAAASUVORK5CYII=", "base64");

const fakeGenerator: ImageGenerator = {
  provider: "fake",
  async generate(request) {
    return {
      bytes: ONE_PX,
      mimeType: "image/png",
      model: "fake-image-model",
      requestId: `fake:${request.prompt}`,
    };
  },
};

async function project(base: string): Promise<any> {
  return fetch(`${base}/api/project`).then((response) => response.json());
}

test("AI Image, original asset rendering, upload dedup and Export Center work end-to-end without network", async () => {
  const root = await mkdtemp(join(tmpdir(), "pitch-e3-editor-e2e-"));
  execFileSync(process.execPath, ["dist/apps/cli/src/index.js", "demo", root], { stdio: "inherit" });
  const { server } = createWorkspaceServer(root, { imageGenerator: fakeGenerator });
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const address = server.address();
  assert(address && typeof address !== "string");
  const base = `http://127.0.0.1:${address.port}`;
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });

  try {
    await page.goto(`${base}/editor-spike`, { waitUntil: "networkidle" });
    await page.getByText("Pitch pointer engine + Daybrush controls attached to live SceneGraph").waitFor();
    await page.locator('[data-e3="ai"]').waitFor();
    await page.locator(".pitch-export-btn").waitFor();

    await page.locator('[data-e3="ai"]').click();
    await page.locator('[data-ai="prompt"]').fill("A precise matte architectural object on a neutral background");
    await page.locator('[data-ai="aspect"]').selectOption("landscape");
    await page.locator('[data-ai="quality"]').selectOption("high");
    await page.locator('[data-ai-action="generate"]').click();
    await page.locator("[data-ai-status]").getByText("Inserted", { exact: false }).waitFor({ timeout: 10_000 });

    await page.waitForFunction(async () => {
      const next = await fetch("/api/project").then((response) => response.json());
      return next.assets.length === 1 && next.deck.slides[0].scene.filter((element: any) => element.type === "image").length === 1;
    });
    let state = await project(base);
    const generated = state.deck.slides[0].scene.find((element: any) => element.type === "image");
    assert(generated);
    assert.equal(generated.origin, "agent");
    assert.equal(state.assets[0].provenance.at(-1).source, "generated");
    await page.locator(`#spikeScene [data-id="${generated.id}"] img[data-pitch-asset="${generated.assetId}"]`).waitFor({ timeout: 10_000 });
    const imageSrc = await page.locator(`#spikeScene [data-id="${generated.id}"] img`).getAttribute("src");
    assert.equal(imageSrc, `/api/assets/${generated.assetId}`);

    await page.locator("[data-modal-close]").click();
    await page.locator('[data-e3="assets"]').click();
    await page.locator(`[data-insert-asset="${generated.assetId}"]`).waitFor();
    await page.locator("[data-modal-close]").click();

    await page.locator('[data-e3-file]').setInputFiles({ name: "same-original.png", mimeType: "image/png", buffer: ONE_PX });
    await page.waitForFunction(async () => {
      const next = await fetch("/api/project").then((response) => response.json());
      return next.assets.length === 1 && next.deck.slides[0].scene.filter((element: any) => element.type === "image").length === 2;
    });
    state = await project(base);
    assert.equal(state.assets.length, 1, "identical uploaded/generated bytes must dedupe to one registry asset");
    assert.equal(state.assets[0].provenance.length, 2, "deduped asset must retain both generated and import provenance events");

    await page.locator(".pitch-export-btn").click();
    const pptx = page.locator('[data-export-card="pptx"]');
    await pptx.locator("[data-export-run]").click();
    await pptx.locator("[data-export-download].visible").waitFor({ timeout: 10_000 });
    assert.match(await pptx.locator("[data-export-status]").textContent() || "", /ready: true/);
    assert.match(await pptx.locator("[data-export-status]").textContent() || "", /unsupported: 0/);

    const figma = page.locator('[data-export-card="figma"]');
    await figma.locator("[data-export-run]").click();
    await figma.locator("[data-export-download].visible").waitFor({ timeout: 10_000 });
    assert.match(await figma.locator("[data-export-status]").textContent() || "", /embedded assets: 1/);

    if (process.platform !== "darwin") {
      const keynote = page.locator('[data-export-card="keynote"]');
      await keynote.locator("[data-export-run]").click();
      await page.waitForFunction(() => {
        const text = document.querySelector('[data-export-card="keynote"] [data-export-status]')?.textContent || "";
        return /macOS|Keynote/i.test(text) && !/Building Keynote/.test(text);
      });
      assert.equal(await keynote.locator("[data-export-download]").evaluate((node) => node.classList.contains("visible")), false);
    }
  } finally {
    await browser.close();
    await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve()));
    await rm(root, { recursive: true, force: true });
  }
});
