import { createHash } from "node:crypto";
import { readFile, rm, writeFile } from "node:fs/promises";
import { extname } from "node:path";
import type { DeckDocument, ImageElement, TableElement } from "../../deck-model/src/index.js";
import { compileDeckToPptx, type PptxCompileResult } from "../../pptx/src/index.js";
import { inflateRawSync } from "node:zlib";

export interface RichAsset { path: string; mimeType?: "image/png" | "image/jpeg"; }
export interface RichCompileOptions { assets: Record<string, RichAsset>; }
export interface RichPptxCompileResult extends PptxCompileResult {
  richElementResults: Array<{ elementId: string; strategy: "native"; kind: "image" | "table"; warnings: string[] }>;
}
const DU_TO_EMU = 914400 / 144;
function emu(value: number): number { return Math.round(value * DU_TO_EMU); }
function xml(value: unknown): string { return String(value ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&apos;"); }
function u16(b: Buffer,o:number):number{return b.readUInt16LE(o)}function u32(b:Buffer,o:number):number{return b.readUInt32LE(o)}
function readZip(buffer:Buffer):Map<string,Buffer>{let eocd=-1;for(let i=buffer.length-22;i>=Math.max(0,buffer.length-65557);i--){if(u32(buffer,i)===0x06054b50){eocd=i;break}}if(eocd<0)throw new Error("ZIP EOCD not found");const count=u16(buffer,eocd+10);let offset=u32(buffer,eocd+16);const result=new Map<string,Buffer>();for(let i=0;i<count;i++){if(u32(buffer,offset)!==0x02014b50)throw new Error("Invalid ZIP central directory");const method=u16(buffer,offset+10),compressedSize=u32(buffer,offset+20),nameLength=u16(buffer,offset+28),extraLength=u16(buffer,offset+30),commentLength=u16(buffer,offset+32),localOffset=u32(buffer,offset+42),name=buffer.subarray(offset+46,offset+46+nameLength).toString("utf8");if(u32(buffer,localOffset)!==0x04034b50)throw new Error(`Invalid local ZIP header ${name}`);const localNameLength=u16(buffer,localOffset+26),localExtraLength=u16(buffer,localOffset+28),start=localOffset+30+localNameLength+localExtraLength,compressed=buffer.subarray(start,start+compressedSize);result.set(name,method===0?Buffer.from(compressed):method===8?inflateRawSync(compressed):(()=>{throw new Error(`Unsupported ZIP compression ${method}`)})());offset+=46+nameLength+extraLength+commentLength}return result}
let crcTable:Uint32Array|undefined;function crc32(data:Buffer):number{if(!crcTable){crcTable=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;crcTable[n]=c>>>0}}let crc=0xffffffff;for(const byte of data)crc=crcTable[(crc^byte)&0xff]^(crc>>>8);return(crc^0xffffffff)>>>0}
function writeZip(entries:Map<string,Buffer>):Buffer{const locals:Buffer[]=[];const centrals:Buffer[]=[];let offset=0;for(const[name,data]of entries){const nameBuf=Buffer.from(name),crc=crc32(data),local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(0,6);local.writeUInt16LE(0,8);local.writeUInt16LE(0,10);local.writeUInt16LE(0,12);local.writeUInt32LE(crc,14);local.writeUInt32LE(data.length,18);local.writeUInt32LE(data.length,22);local.writeUInt16LE(nameBuf.length,26);local.writeUInt16LE(0,28);locals.push(local,nameBuf,data);const central=Buffer.alloc(46);central.writeUInt32LE(0x02014b50,0);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt16LE(0,8);central.writeUInt16LE(0,10);central.writeUInt16LE(0,12);central.writeUInt16LE(0,14);central.writeUInt32LE(crc,16);central.writeUInt32LE(data.length,20);central.writeUInt32LE(data.length,24);central.writeUInt16LE(nameBuf.length,28);central.writeUInt16LE(0,30);central.writeUInt16LE(0,32);central.writeUInt16LE(0,34);central.writeUInt16LE(0,36);central.writeUInt32LE(0,38);central.writeUInt32LE(offset,42);centrals.push(central,nameBuf);offset+=30+nameBuf.length+data.length}const centralData=Buffer.concat(centrals),localData=Buffer.concat(locals),eocd=Buffer.alloc(22);eocd.writeUInt32LE(0x06054b50,0);eocd.writeUInt16LE(0,4);eocd.writeUInt16LE(0,6);eocd.writeUInt16LE(entries.size,8);eocd.writeUInt16LE(entries.size,10);eocd.writeUInt32LE(centralData.length,12);eocd.writeUInt32LE(localData.length,16);eocd.writeUInt16LE(0,20);return Buffer.concat([localData,centralData,eocd])}
function ensureContentType(content:string,ext:string,mime:string):string{if(new RegExp(`<Default[^>]+Extension=[\"']${ext}[\"']`,'i').test(content))return content;return content.replace('</Types>',`<Default Extension="${ext}" ContentType="${mime}"/></Types>`)}
function relsRoot():string{return'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>'}
function addRelationship(rels:string,id:string,target:string):string{return rels.replace('</Relationships>',`<Relationship Id="${id}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="${xml(target)}"/></Relationships>`)}
function cropRect(image:ImageElement):string{if(!image.crop)return'';const c=image.crop,cv=(v:number)=>Math.max(0,Math.min(100000,Math.round(v<=1?v*100000:v)));return`<a:srcRect l="${cv(c.left)}" t="${cv(c.top)}" r="${cv(c.right)}" b="${cv(c.bottom)}"/>`}
function pictureXml(image:ImageElement,relId:string,shapeId:number,name:string):string{const g=image.geometry;return`<p:pic><p:nvPicPr><p:cNvPr id="${shapeId}" name="${xml(name)}"/><p:cNvPicPr><a:picLocks noChangeAspect="1"/></p:cNvPicPr><p:nvPr/></p:nvPicPr><p:blipFill><a:blip r:embed="${relId}"/>${cropRect(image)}<a:stretch><a:fillRect/></a:stretch></p:blipFill><p:spPr><a:xfrm><a:off x="${emu(g.x)}" y="${emu(g.y)}"/><a:ext cx="${emu(g.width)}" cy="${emu(g.height)}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr></p:pic>`}
function cellXml(text:string):string{return`<a:tc><a:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="en-US" sz="1800"/><a:t>${xml(text)}</a:t></a:r><a:endParaRPr lang="en-US" sz="1800"/></a:p></a:txBody><a:tcPr/></a:tc>`}
function tableXml(table:TableElement,shapeId:number):string{const g=table.geometry,rows=table.rows.length||1,cols=Math.max(1,...table.rows.map(r=>r.length)),widths=table.columnWidths?.length===cols?table.columnWidths:Array.from({length:cols},()=>1/cols),sum=widths.reduce((a,b)=>a+b,0)||1,colXml=widths.map(w=>`<a:gridCol w="${Math.round(emu(g.width)*(w/sum))}"/>`).join(''),rowHeight=Math.round(emu(g.height)/rows),rowsXml=table.rows.map(row=>`<a:tr h="${rowHeight}">${Array.from({length:cols},(_,i)=>cellXml(row[i]?.text??'' )).join('')}</a:tr>`).join('');return`<p:graphicFrame><p:nvGraphicFramePr><p:cNvPr id="${shapeId}" name="${xml(table.name||table.id)}"/><p:cNvGraphicFramePr/><p:nvPr/></p:nvGraphicFramePr><p:xfrm><a:off x="${emu(g.x)}" y="${emu(g.y)}"/><a:ext cx="${emu(g.width)}" cy="${emu(g.height)}"/></p:xfrm><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/table"><a:tbl><a:tblPr firstRow="1" bandRow="1"><a:tableStyleId>{5C22544A-7EE6-4342-B048-85BDC9FD1C3A}</a:tableStyleId></a:tblPr><a:tblGrid>${colXml}</a:tblGrid>${rowsXml}</a:tbl></a:graphicData></a:graphic></p:graphicFrame>`}
function inject(xmlText:string,fragment:string):string{if(!xmlText.includes('</p:spTree>'))throw new Error('Slide spTree not found');return xmlText.replace('</p:spTree>',`${fragment}</p:spTree>`)}
function mimeFor(asset:RichAsset):{mime:string;ext:string}{if(asset.mimeType==='image/png')return{mime:'image/png',ext:'png'};if(asset.mimeType==='image/jpeg')return{mime:'image/jpeg',ext:'jpg'};const ext=extname(asset.path).toLowerCase();if(ext==='.png')return{mime:'image/png',ext:'png'};if(ext==='.jpg'||ext==='.jpeg')return{mime:'image/jpeg',ext:'jpg'};throw new Error(`Unsupported image asset: ${asset.path}`)}

export async function compileRichDeckToPptx(deck:DeckDocument,outputPath:string,options:RichCompileOptions):Promise<RichPptxCompileResult>{
  const basePath=`${outputPath}.base-${Date.now()}.pptx`;
  const richBySlide=deck.slides.map(slide=>slide.scene.filter((e):e is ImageElement|TableElement=>e.type==='image'||e.type==='table'));
  const baseDeck:DeckDocument={...deck,slides:deck.slides.map(slide=>({...slide,scene:slide.scene.filter(e=>e.type!=='image'&&e.type!=='table')}))};
  const base=await compileDeckToPptx(baseDeck,basePath);const entries=readZip(await readFile(basePath));let contentTypes=entries.get('[Content_Types].xml')?.toString('utf8')??'';const richElementResults:RichPptxCompileResult['richElementResults']=[];let mediaIndex=1;
  for(let slideIndex=0;slideIndex<deck.slides.length;slideIndex++){
    const rich=richBySlide[slideIndex];if(!rich.length)continue;const slidePath=`ppt/slides/slide${slideIndex+1}.xml`,relsPath=`ppt/slides/_rels/slide${slideIndex+1}.xml.rels`;let slideXml=entries.get(slidePath)?.toString('utf8');if(!slideXml)throw new Error(`Missing ${slidePath}`);let rels=entries.get(relsPath)?.toString('utf8')??relsRoot();let relIndex=100;
    for(const element of rich){if(element.type==='image'){const asset=options.assets[element.assetId];if(!asset)throw new Error(`Missing image asset ${element.assetId}`);const {mime,ext}=mimeFor(asset),mediaName=`image${mediaIndex++}.${ext}`,mediaPath=`ppt/media/${mediaName}`,relId=`rIdRich${relIndex++}`;entries.set(mediaPath,await readFile(asset.path));contentTypes=ensureContentType(contentTypes,ext,mime);rels=addRelationship(rels,relId,`../media/${mediaName}`);slideXml=inject(slideXml,pictureXml(element,relId,2000+relIndex,element.name||element.id));richElementResults.push({elementId:element.id,strategy:'native',kind:'image',warnings:[]})}else{slideXml=inject(slideXml,tableXml(element,3000+relIndex++));richElementResults.push({elementId:element.id,strategy:'native',kind:'table',warnings:[]})}}
    entries.set(slidePath,Buffer.from(slideXml,'utf8'));entries.set(relsPath,Buffer.from(rels,'utf8'));
  }
  entries.set('[Content_Types].xml',Buffer.from(contentTypes,'utf8'));const out=writeZip(entries);await writeFile(outputPath,out);await rm(basePath,{force:true});
  return{...base,outputPath,contentHash:createHash('sha256').update(out).digest('hex'),elementResults:[...base.elementResults,...richElementResults.map(x=>({elementId:x.elementId,strategy:x.strategy,warnings:x.warnings}))],richElementResults};
}
