import type { DeckDocument, SceneElement, TextElement } from "../../deck-model/src/index.js";
function esc(v:string):string{return v.replace(/[&<>\"]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"} as any)[c]??c);}
function style(el:SceneElement):string{const g=el.geometry;return `position:absolute;left:${g.x}px;top:${g.y}px;width:${g.width}px;height:${g.height}px;transform:rotate(${g.rotation??0}deg);opacity:${el.opacity??1};z-index:${el.zIndex};`;}
function textHtml(el:TextElement):string{const paras=el.paragraphs.map(p=>`<p style="margin:0;${p.align?`text-align:${p.align};`:""}">${p.runs.map(r=>`<span style="${r.bold?"font-weight:700;":""}${r.italic?"font-style:italic;":""}${r.color?`color:${r.color};`:""}${r.fontFamily?`font-family:${esc(r.fontFamily)};`:""}${r.fontSizePt?`font-size:${r.fontSizePt*96/72}px;`:""}">${esc(r.text)}</span>`).join("")}</p>`).join("");return `<div class="el text" data-pitch-element-id="${esc(el.id)}" style="${style(el)}display:flex;flex-direction:column;justify-content:${el.verticalAlign==="middle"?"center":el.verticalAlign==="bottom"?"flex-end":"flex-start"};overflow:hidden;">${paras}</div>`;}
function elementHtml(el:SceneElement):string{
  if(el.type==="text")return textHtml(el);
  if(el.type==="shape")return `<div class="el shape" data-pitch-element-id="${esc(el.id)}" style="${style(el)}background:${esc(el.fill??"transparent")};border:${el.stroke?`${el.stroke.widthDU}px solid ${esc(el.stroke.color)}`:"none"};border-radius:${el.shape==="ellipse"?"50%":`${el.radiusDU??0}px`};"></div>`;
  if(el.type==="line")return `<svg class="el line" data-pitch-element-id="${esc(el.id)}" style="${style(el)}overflow:visible"><line x1="${el.start[0]}" y1="${el.start[1]}" x2="${el.end[0]}" y2="${el.end[1]}" stroke="${esc(el.stroke.color)}" stroke-width="${el.stroke.widthDU}" /></svg>`;
  if(el.type==="image")return `<div class="el image" data-pitch-element-id="${esc(el.id)}" style="${style(el)}background:#222;display:grid;place-items:center;color:#777;font:24px system-ui">image:${esc(el.assetId)}</div>`;
  if(el.type==="chart")return `<div class="el chart" data-pitch-element-id="${esc(el.id)}" style="${style(el)}border:1px solid #30343b;padding:18px;font:24px system-ui">Chart · ${esc(el.chart.chartType)}<br><small>${esc(el.chart.insightStatement)}</small></div>`;
  if(el.type==="table")return `<div class="el table" data-pitch-element-id="${esc(el.id)}" style="${style(el)}border:1px solid #30343b;font:18px system-ui">${el.rows.map(r=>`<div>${r.map(c=>esc(c.text)).join(" · ")}</div>`).join("")}</div>`;
  return `<div class="el" data-pitch-element-id="${esc(el.id)}" style="${style(el)}border:1px dashed #555"></div>`;
}
export function renderDeckHtml(deck:DeckDocument):string{
  const slides=deck.slides.sort((a,b)=>a.order-b.order).map((slide,i)=>`<section class="slide-wrap"><div class="slide" data-pitch-slide-id="${esc(slide.id)}" style="width:${deck.canvas.widthDU}px;height:${deck.canvas.heightDU}px">${slide.scene.sort((a,b)=>a.zIndex-b.zIndex).map(elementHtml).join("")}</div><div class="meta"><b>${i+1}. ${esc(slide.title)}</b><span>${esc(slide.semantic.takeaway)}</span></div></section>`).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(deck.title)}</title><style>*{box-sizing:border-box}body{margin:0;background:#0d0f12;color:#eee;font-family:Inter,system-ui,sans-serif}.toolbar{position:sticky;top:0;padding:14px 20px;background:#11151bcc;border-bottom:1px solid #252b33;backdrop-filter:blur(12px);z-index:10}.deck{padding:30px;display:grid;gap:38px;justify-items:center}.slide-wrap{width:min(96vw,1280px)}.slide{position:relative;background:#fff;color:#111;transform-origin:top left;zoom:calc(min(96vw,1280px)/1920);overflow:hidden;box-shadow:0 24px 80px #0008}.meta{display:flex;gap:16px;margin-top:10px;color:#a9b0ba}.meta span{margin-left:auto}.el{cursor:default}</style></head><body><div class="toolbar">PitchOS Preview · ${esc(deck.title)}</div><main class="deck">${slides}</main></body></html>`;
}
