import { writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import type { DeckDocument, SceneElement, ShapeElement, TextElement, LineElement } from "../../deck-model/src/index.js";

export const STANDARD_WIDE = { widthDU: 1920, heightDU: 1080, duPerInch: 144 } as const;
export const EMU_PER_DU = 914400 / STANDARD_WIDE.duPerInch;
export function duToInches(valueDU: number): number { return valueDU / STANDARD_WIDE.duPerInch; }
export function duToEmu(valueDU: number): number { return Math.round(valueDU * EMU_PER_DU); }

export type PptxElementResult = { elementId: string; strategy: "native" | "vector" | "rasterFallback" | "unsupported"; warnings: string[]; };
export interface PptxCompileResult { outputPath: string; slideCount: number; elementResults: PptxElementResult[]; warnings: string[]; contentHash: string; }
export interface RoundTripDiff { slideId: string; elementId?: string; kind: "missing" | "textChanged" | "geometryDrift" | "styleDrift" | "downgraded" | "extra"; severity: "minor" | "major" | "critical"; message: string; }
export interface PptxCompiler { compile(deckArtifactPath: string, outputPath: string): Promise<PptxCompileResult>; }
export interface PptxRoundTripValidator { compare(canonicalDeckPath: string, exportedPptxPath: string): Promise<RoundTripDiff[]>; }

type ZipEntry = { name: string; data: Buffer };

const CRC_TABLE = (() => {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = (c & 1) ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c >>> 0;
  }
  return table;
})();
function crc32(buf: Buffer): number {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}
function u16(v:number){const b=Buffer.alloc(2);b.writeUInt16LE(v&0xffff,0);return b;}
function u32(v:number){const b=Buffer.alloc(4);b.writeUInt32LE(v>>>0,0);return b;}
function zipStore(entries: ZipEntry[]): Buffer {
  const locals: Buffer[]=[]; const centrals: Buffer[]=[]; let offset=0;
  for(const e of entries){
    const name=Buffer.from(e.name,"utf8"); const data=e.data; const crc=crc32(data);
    const local=Buffer.concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);
    locals.push(local);
    const central=Buffer.concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]);
    centrals.push(central); offset+=local.length;
  }
  const central=Buffer.concat(centrals); const local=Buffer.concat(locals);
  const end=Buffer.concat([u32(0x06054b50),u16(0),u16(0),u16(entries.length),u16(entries.length),u32(central.length),u32(local.length),u16(0)]);
  return Buffer.concat([local,central,end]);
}

function xml(v:string):string{return v.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&apos;");}
function hex(color:string|undefined,fallback="000000"):string { const c=(color??"").replace(/^#/,"").toUpperCase(); return /^[0-9A-F]{6}$/.test(c)?c:fallback; }
function xfrm(el:SceneElement):string { const g=el.geometry; const rot=g.rotation?` rot="${Math.round(g.rotation*60000)}"`:""; return `<a:xfrm${rot}><a:off x="${duToEmu(g.x)}" y="${duToEmu(g.y)}"/><a:ext cx="${duToEmu(g.width)}" cy="${duToEmu(g.height)}"/></a:xfrm>`; }
function runXml(run:{text:string;bold?:boolean;italic?:boolean;color?:string;fontFamily?:string;fontSizePt?:number}):string { const attrs=[run.bold?' b="1"':'',run.italic?' i="1"':'',` sz="${Math.round((run.fontSizePt??18)*100)}"`].join(""); const color=`<a:solidFill><a:srgbClr val="${hex(run.color,"000000")}"/></a:solidFill>`; const font=run.fontFamily?`<a:latin typeface="${xml(run.fontFamily)}"/><a:ea typeface="${xml(run.fontFamily)}"/><a:cs typeface="${xml(run.fontFamily)}"/>`:""; return `<a:r><a:rPr lang="en-US"${attrs}>${color}${font}</a:rPr><a:t>${xml(run.text)}</a:t></a:r>`; }
function textShape(el:TextElement,id:number):string { const paragraphs=el.paragraphs.map(p=>{const algn=p.align?` algn="${p.align==='center'?'ctr':p.align==='justify'?'just':p.align}"`:"";return `<a:p><a:pPr${algn}/>${p.runs.map(runXml).join("")}<a:endParaRPr lang="en-US"/></a:p>`;}).join(""); return `<p:sp><p:nvSpPr><p:cNvPr id="${id}" name="${xml(el.name??el.id)}"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr>${xfrm(el)}<a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr wrap="square" anchor="${el.verticalAlign==='middle'?'ctr':el.verticalAlign==='bottom'?'b':'t'}"/><a:lstStyle/>${paragraphs}</p:txBody></p:sp>`; }
function shapeXml(el:ShapeElement,id:number):string { const prst=el.shape==='roundRect'?'roundRect':el.shape==='ellipse'?'ellipse':el.shape==='triangle'?'triangle':'rect'; const fill=el.fill?`<a:solidFill><a:srgbClr val="${hex(el.fill,"FFFFFF")}"/></a:solidFill>`:'<a:noFill/>'; const ln=el.stroke?`<a:ln w="${Math.max(1,duToEmu(el.stroke.widthDU))}"><a:solidFill><a:srgbClr val="${hex(el.stroke.color)}"/></a:solidFill></a:ln>`:'<a:ln><a:noFill/></a:ln>'; return `<p:sp><p:nvSpPr><p:cNvPr id="${id}" name="${xml(el.name??el.id)}"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr>${xfrm(el)}<a:prstGeom prst="${prst}"><a:avLst/></a:prstGeom>${fill}${ln}</p:spPr></p:sp>`; }
function lineXml(el:LineElement,id:number):string { const color=hex(el.stroke.color); return `<p:cxnSp><p:nvCxnSpPr><p:cNvPr id="${id}" name="${xml(el.name??el.id)}"/><p:cNvCxnSpPr/><p:nvPr/></p:nvCxnSpPr><p:spPr>${xfrm(el)}<a:prstGeom prst="line"><a:avLst/></a:prstGeom><a:ln w="${Math.max(1,duToEmu(el.stroke.widthDU))}"><a:solidFill><a:srgbClr val="${color}"/></a:solidFill>${el.startMarker==='arrow'?'<a:headEnd type="triangle"/>':''}${el.endMarker==='arrow'?'<a:tailEnd type="triangle"/>':''}</a:ln></p:spPr></p:cxnSp>`; }
function slideXml(deck:DeckDocument,slide:DeckDocument['slides'][number]):{xml:string;results:PptxElementResult[]} { let id=2; const results:PptxElementResult[]=[]; const body:string[]=[]; for(const el of [...slide.scene].sort((a,b)=>a.zIndex-b.zIndex)){ if(el.type==='text'){body.push(textShape(el,id++));results.push({elementId:el.id,strategy:'native',warnings:[]});} else if(el.type==='shape'){body.push(shapeXml(el,id++));results.push({elementId:el.id,strategy:'native',warnings:[]});} else if(el.type==='line'){body.push(lineXml(el,id++));results.push({elementId:el.id,strategy:'native',warnings:[]});} else {results.push({elementId:el.id,strategy:'unsupported',warnings:[`Minimal compiler does not yet emit ${el.type}`]});} }
  const s=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>${body.join("")}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`; return {xml:s,results}; }
function themeXml():string{return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="PitchOS"><a:themeElements><a:clrScheme name="PitchOS"><a:dk1><a:srgbClr val="000000"/></a:dk1><a:lt1><a:srgbClr val="FFFFFF"/></a:lt1><a:dk2><a:srgbClr val="1F1F1F"/></a:dk2><a:lt2><a:srgbClr val="F2F2F2"/></a:lt2><a:accent1><a:srgbClr val="4472C4"/></a:accent1><a:accent2><a:srgbClr val="ED7D31"/></a:accent2><a:accent3><a:srgbClr val="A5A5A5"/></a:accent3><a:accent4><a:srgbClr val="FFC000"/></a:accent4><a:accent5><a:srgbClr val="5B9BD5"/></a:accent5><a:accent6><a:srgbClr val="70AD47"/></a:accent6><a:hlink><a:srgbClr val="0563C1"/></a:hlink><a:folHlink><a:srgbClr val="954F72"/></a:folHlink></a:clrScheme><a:fontScheme name="PitchOS"><a:majorFont><a:latin typeface="Aptos Display"/><a:ea typeface=""/><a:cs typeface=""/></a:majorFont><a:minorFont><a:latin typeface="Aptos"/><a:ea typeface=""/><a:cs typeface=""/></a:minorFont></a:fontScheme><a:fmtScheme name="PitchOS"><a:fillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:fillStyleLst><a:lnStyleLst><a:ln w="6350"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln><a:ln w="12700"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln><a:ln w="19050"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln></a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst><a:bgFillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:bgFillStyleLst></a:fmtScheme></a:themeElements><a:objectDefaults/><a:extraClrSchemeLst/></a:theme>`;}
function masterXml():string{return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMap accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" bg1="lt1" bg2="lt2" folHlink="folHlink" hlink="hlink" tx1="dk1" tx2="dk2"/><p:sldLayoutIdLst><p:sldLayoutId id="1" r:id="rId1"/></p:sldLayoutIdLst><p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles></p:sldMaster>`;}
function layoutXml():string{return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank" preserve="1"><p:cSld name="Blank"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>`;}

export async function compileDeckToPptx(deck:DeckDocument,outputPath:string):Promise<PptxCompileResult>{
  const entries:ZipEntry[]=[]; const add=(name:string,s:string)=>entries.push({name,data:Buffer.from(s,"utf8")}); const slideResults:PptxElementResult[]=[];
  const slideOverrides=deck.slides.map((_,i)=>`<Override PartName="/ppt/slides/slide${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`).join("");
  add("[Content_Types].xml",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/><Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>${slideOverrides}<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>`);
  add("_rels/.rels",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>`);
  const sldIds=deck.slides.map((_,i)=>`<p:sldId id="${256+i}" r:id="rId${i+2}"/>`).join("");
  add("ppt/presentation.xml",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst><p:sldIdLst>${sldIds}</p:sldIdLst><p:sldSz cx="${duToEmu(deck.canvas.widthDU)}" cy="${duToEmu(deck.canvas.heightDU)}"/><p:notesSz cx="6858000" cy="9144000"/></p:presentation>`);
  const rels=[`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/>`,...deck.slides.map((_,i)=>`<Relationship Id="rId${i+2}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide${i+1}.xml"/>`)].join("");
  add("ppt/_rels/presentation.xml.rels",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${rels}</Relationships>`);
  add("ppt/slideMasters/slideMaster1.xml",masterXml()); add("ppt/slideMasters/_rels/slideMaster1.xml.rels",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/></Relationships>`); add("ppt/slideLayouts/slideLayout1.xml",layoutXml()); add("ppt/slideLayouts/_rels/slideLayout1.xml.rels",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="../slideMasters/slideMaster1.xml"/></Relationships>`); add("ppt/theme/theme1.xml",themeXml());
  deck.slides.forEach((slide,i)=>{const built=slideXml(deck,slide);slideResults.push(...built.results);add(`ppt/slides/slide${i+1}.xml`,built.xml);add(`ppt/slides/_rels/slide${i+1}.xml.rels`,`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/></Relationships>`);});
  const now=new Date().toISOString(); add("docProps/core.xml",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>${xml(deck.title)}</dc:title><dc:creator>Pitch Monumentum</dc:creator><dcterms:created xsi:type="dcterms:W3CDTF">${now}</dcterms:created><dcterms:modified xsi:type="dcterms:W3CDTF">${now}</dcterms:modified></cp:coreProperties>`); add("docProps/app.xml",`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Application>Pitch Monumentum</Application><Slides>${deck.slides.length}</Slides><PresentationFormat>Widescreen</PresentationFormat></Properties>`);
  const zip=zipStore(entries); await writeFile(outputPath,zip); const contentHash=createHash("sha256").update(zip).digest("hex"); const warnings=slideResults.flatMap(r=>r.warnings); return {outputPath,slideCount:deck.slides.length,elementResults:slideResults,warnings,contentHash};
}
